"""Database Knowledgebase Exceptions Package"""

from .errors import (
    DatabaseKnowledgebaseError,
    DatabaseConnectionError,
    DatabaseAuthenticationError,
    UnsupportedDatabaseError,
    SchemaIntrospectionError,
    DatabasePermissionError,
    DatabaseTimeoutError,
    InvalidDatabaseConfigError,
    TenantMismatchError,
    SchemaParsingError,
    DatabaseKnowledgebaseNotFoundError,
    SchemaSnapshotNotFoundError,
    SchemaVersionMismatchError,
    QueryPlanError,
    SQLSyntaxError,
    SQLValidationError,
)
from ..execution.errors import (
    ExecutionPolicyViolation,
    ParameterBindingError,
    QueryConnectionError,
    QueryExecutionError,
    QueryExecutionTimeout,
    ResultLimitExceeded,
    ResultValidationError,
    StaleSchemaVersionError,
    TenantExecutionDenied,
)

from ..answering.errors import (
    AnswerRepairExhausted,
    AnswerSynthesisError,
    GroundingViolationError,
    NumericalMismatchError,
    PromptInjectionDetected,
)

__all__ = [
    "DatabaseKnowledgebaseError",
    "DatabaseConnectionError",
    "DatabaseAuthenticationError",
    "UnsupportedDatabaseError",
    "SchemaIntrospectionError",
    "DatabasePermissionError",
    "DatabaseTimeoutError",
    "InvalidDatabaseConfigError",
    "TenantMismatchError",
    "SchemaParsingError",
    "DatabaseKnowledgebaseNotFoundError",
    "SchemaSnapshotNotFoundError",
    "SchemaVersionMismatchError",
    "QueryPlanError",
    "SQLSyntaxError",
    "SQLValidationError",
    "ExecutionPolicyViolation",
    "ParameterBindingError",
    "QueryConnectionError",
    "QueryExecutionError",
    "QueryExecutionTimeout",
    "ResultLimitExceeded",
    "ResultValidationError",
    "StaleSchemaVersionError",
    "TenantExecutionDenied",
    "AnswerRepairExhausted",
    "AnswerSynthesisError",
    "GroundingViolationError",
    "NumericalMismatchError",
    "PromptInjectionDetected",
]
