import re
import logging
from typing import List
from app.modules.rag.pipeline import RAGContext

logger = logging.getLogger(__name__)

class NumericValidator:
    """
    Validates that any numbers generated by the LLM were actually present in the retrieved context.
    """
    
    def __init__(self):
        # Matches numbers like 1.1%, 10.9%, 1,000, 4.5M, etc.
        self.number_pattern = re.compile(r'\b\d{1,3}(?:,\d{3})*(?:\.\d+)?(?:%|M|B|K)?\b')
        
    def validate(self, generated_text: str, context: RAGContext) -> bool:
        """
        Returns True if the generated text is numerically consistent with the context.
        Returns False if a hallucinated number is detected.
        """
        generated_numbers = set(self.number_pattern.findall(generated_text))
        
        # If no numbers generated, it's valid
        if not generated_numbers:
            return True
            
        # Extract all numbers from the context chunks
        context_text = " ".join([c.text for c in context.chunks])
        context_numbers = set(self.number_pattern.findall(context_text))
        
        # Check if all generated numbers are in the context
        # (This is a strict heuristic and might false positive on calculated math like '2024' or basic math, 
        # but prevents 1.1% instead of 10.9% hallucination)
        for num in generated_numbers:
            # We allow small numbers (e.g., years, list items) to bypass strict check
            try:
                clean_num = float(num.replace('%', '').replace(',', '').replace('M', '').replace('B', '').replace('K', ''))
                if clean_num < 2050 and clean_num > 1900: # Allow years
                    continue
                if clean_num < 10 and num.isdigit(): # Allow small integers (lists, counts)
                    continue
            except ValueError:
                pass
                
            if num not in context_numbers:
                # Normalization check: handle space-separated vs comma-separated numbers (e.g., "3 000" vs "3,000")
                num_digits_only = re.sub(r'[\s,]', '', num)
                context_digits_only = re.sub(r'(\d)[\s,](\d)', r'\1\2', context_text)
                if num_digits_only and num_digits_only in context_digits_only:
                    continue

                logger.warning(f"Hallucination detected! Number '{num}' not found in context.")
                return False
                
        return True
