"""Alembic script template"""
"""Add Enterprise Audit metrics

Revision ID: 111989731a94
Revises: 1e5eddefd2df
Create Date: 2026-07-03 15:58:35.004853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '111989731a94'
down_revision = '1e5eddefd2df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('document_ingestion_runs', sa.Column('source_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('document_type_detected', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('parser_name', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('chunking_strategy', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('embedding_model', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('graph_extractor_model', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('validation_version', sa.String(length=20), server_default='v1.3', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('original_pages', sa.Integer(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('original_chars', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('original_words', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('chunk_reconstruction_chars', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('stored_chunk_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('vector_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_entities_extracted', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_entities_saved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_relationships_extracted', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_relationships_saved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('reconstruction_similarity', sa.Float(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('retrieval_samples_tested', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('retrieval_samples_successful', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('retrieval_validation_score', sa.Float(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('retrieval_validation_passed', sa.Boolean(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('validation_failure_reason', sa.Text(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('integrity_score', sa.Integer(), nullable=True))
    op.add_column('document_ingestion_runs', sa.Column('chunking_time_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('embedding_time_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_extraction_time_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('vector_insert_time_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('graph_insert_time_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('validation_time_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('document_ingestion_runs', sa.Column('total_processing_time_ms', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_ingestion_runs', 'total_processing_time_ms')
    op.drop_column('document_ingestion_runs', 'validation_time_ms')
    op.drop_column('document_ingestion_runs', 'graph_insert_time_ms')
    op.drop_column('document_ingestion_runs', 'vector_insert_time_ms')
    op.drop_column('document_ingestion_runs', 'graph_extraction_time_ms')
    op.drop_column('document_ingestion_runs', 'embedding_time_ms')
    op.drop_column('document_ingestion_runs', 'chunking_time_ms')
    op.drop_column('document_ingestion_runs', 'integrity_score')
    op.drop_column('document_ingestion_runs', 'validation_failure_reason')
    op.drop_column('document_ingestion_runs', 'validation_status')
    op.drop_column('document_ingestion_runs', 'retrieval_validation_passed')
    op.drop_column('document_ingestion_runs', 'retrieval_validation_score')
    op.drop_column('document_ingestion_runs', 'retrieval_samples_successful')
    op.drop_column('document_ingestion_runs', 'retrieval_samples_tested')
    op.drop_column('document_ingestion_runs', 'reconstruction_similarity')
    op.drop_column('document_ingestion_runs', 'graph_relationships_saved')
    op.drop_column('document_ingestion_runs', 'graph_relationships_extracted')
    op.drop_column('document_ingestion_runs', 'graph_entities_saved')
    op.drop_column('document_ingestion_runs', 'graph_entities_extracted')
    op.drop_column('document_ingestion_runs', 'vector_count')
    op.drop_column('document_ingestion_runs', 'stored_chunk_count')
    op.drop_column('document_ingestion_runs', 'chunk_reconstruction_chars')
    op.drop_column('document_ingestion_runs', 'original_words')
    op.drop_column('document_ingestion_runs', 'original_chars')
    op.drop_column('document_ingestion_runs', 'original_pages')
    op.drop_column('document_ingestion_runs', 'validation_version')
    op.drop_column('document_ingestion_runs', 'graph_extractor_model')
    op.drop_column('document_ingestion_runs', 'embedding_model')
    op.drop_column('document_ingestion_runs', 'chunking_strategy')
    op.drop_column('document_ingestion_runs', 'parser_name')
    op.drop_column('document_ingestion_runs', 'document_type_detected')
    op.drop_column('document_ingestion_runs', 'source_fingerprint')


    # ### end Alembic commands ###
