"""Alembic script template"""
"""add_kb_id_to_processing_jobs

Revision ID: 1acc31aed8cc
Revises: ba0c1c521487
Create Date: 2026-07-06 14:06:59.170681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acc31aed8cc'
down_revision = 'ba0c1c521487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('kb_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'kb_id')
    # ### end Alembic commands ###
