"""Alembic script template"""
"""add metadata_json

Revision ID: 1e5eddefd2df
Revises: f6a7fd0e3869
Create Date: 2026-06-30 16:46:57.252793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e5eddefd2df'
down_revision = 'f6a7fd0e3869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('knowledge_bases', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('document_chunks', 'metadata_json')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
