"""Alembic script template"""
"""Add summary_embedding to KnowledgeBase for semantic routing

Revision ID: a816e735db90
Revises: a2089ae9aacb
Create Date: 2026-08-25 14:51:45.218355

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a816e735db90'
down_revision = 'a2089ae9aacb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_widget_customizations_created_at', table_name='widget_customizations')
    op.drop_index('ix_widget_customizations_id', table_name='widget_customizations')
    op.drop_index('ix_widget_customizations_tenant_id', table_name='widget_customizations')
    op.drop_index('ix_widget_customizations_updated_at', table_name='widget_customizations')
    op.drop_table('widget_customizations')
    op.drop_index('idx_memory_scoping_v2', table_name='episodic_memories')
    op.drop_index('ix_episodic_memories_agent_id', table_name='episodic_memories')
    op.drop_index('ix_episodic_memories_session_id', table_name='episodic_memories')
    op.drop_index('ix_episodic_memories_tenant_id', table_name='episodic_memories')
    op.drop_index('ix_episodic_memories_user_id', table_name='episodic_memories')
    op.drop_table('episodic_memories')
    op.drop_index('idx_user_preferences_scoping_v2', table_name='user_preferences')
    op.drop_index('ix_user_preferences_agent_id', table_name='user_preferences')
    op.drop_index('ix_user_preferences_tenant_id', table_name='user_preferences')
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.add_column('knowledge_bases', sa.Column('summary_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=4096), nullable=True))
    op.drop_index('ix_kbs_file_hash', table_name='knowledge_bases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_kbs_file_hash', 'knowledge_bases', ['file_hash'], unique=False)
    op.drop_column('knowledge_bases', 'summary_embedding')
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('preference_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('preference_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_statement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_preferences_pkey')
    )
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    op.create_index('ix_user_preferences_tenant_id', 'user_preferences', ['tenant_id'], unique=False)
    op.create_index('ix_user_preferences_agent_id', 'user_preferences', ['agent_id'], unique=False)
    op.create_index('idx_user_preferences_scoping_v2', 'user_preferences', ['tenant_id', 'user_id', 'agent_id', 'preference_key'], unique=False)
    op.create_table('episodic_memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summarization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_vector', pgvector.sqlalchemy.vector.VECTOR(dim=4096), autoincrement=False, nullable=True),
    sa.Column('summary_vector', pgvector.sqlalchemy.vector.VECTOR(dim=4096), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='episodic_memories_pkey')
    )
    op.create_index('ix_episodic_memories_user_id', 'episodic_memories', ['user_id'], unique=False)
    op.create_index('ix_episodic_memories_tenant_id', 'episodic_memories', ['tenant_id'], unique=False)
    op.create_index('ix_episodic_memories_session_id', 'episodic_memories', ['session_id'], unique=False)
    op.create_index('ix_episodic_memories_agent_id', 'episodic_memories', ['agent_id'], unique=False)
    op.create_index('idx_memory_scoping_v2', 'episodic_memories', ['tenant_id', 'user_id', 'session_id'], unique=False)
    op.create_table('widget_customizations',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('show_in_header', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('show_in_chat', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('show_in_embed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='widget_customizations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='widget_customizations_pkey')
    )
    op.create_index('ix_widget_customizations_updated_at', 'widget_customizations', ['updated_at'], unique=False)
    op.create_index('ix_widget_customizations_tenant_id', 'widget_customizations', ['tenant_id'], unique=False)
    op.create_index('ix_widget_customizations_id', 'widget_customizations', ['id'], unique=False)
    op.create_index('ix_widget_customizations_created_at', 'widget_customizations', ['created_at'], unique=False)
    # ### end Alembic commands ###
