"""Alembic script template"""
"""Add cache hits and kg extraction calls telemetry

Revision ID: ba0c1c521487
Revises: be532ab954d5
Create Date: 2026-07-06 11:49:53.085942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Alembic script template"""
"""Add cache hits and kg extraction calls telemetry

Revision ID: ba0c1c521487
Revises: be532ab954d5
Create Date: 2026-07-06 11:49:53.085942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0c1c521487'
down_revision = 'be532ab954d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ingestion_runs', sa.Column('cache_hits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('document_ingestion_runs', sa.Column('kg_extraction_calls', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_ingestion_runs', 'kg_extraction_calls')
    op.drop_column('document_ingestion_runs', 'cache_hits')
    # ### end Alembic commands ###
