"""Alembic script template"""
"""Add routing metrics to ingestion runs

Revision ID: be532ab954d5
Revises: a123b456c789
Create Date: 2026-07-06 11:40:09.669498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Alembic script template"""
"""Add routing metrics to ingestion runs

Revision ID: be532ab954d5
Revises: a123b456c789
Create Date: 2026-07-06 11:40:09.669498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be532ab954d5'
down_revision = 'a123b456c789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ingestion_runs', sa.Column('fluff_chunks_skipped', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('document_ingestion_runs', sa.Column('processed_chunks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('document_ingestion_runs', sa.Column('routing_version', sa.String(length=50), nullable=True, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_ingestion_runs', 'routing_version')
    op.drop_column('document_ingestion_runs', 'processed_chunks')
    op.drop_column('document_ingestion_runs', 'fluff_chunks_skipped')
    # ### end Alembic commands ###
