"""Alembic script template"""
"""Add noisy_words to knowledge_bases

Revision ID: de22325e9f67
Revises: 1acc31aed8cc
Create Date: 2026-07-17 22:28:43.559647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de22325e9f67'
down_revision = '1acc31aed8cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('noisy_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('knowledge_bases', sa.Column('noisy_words_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_kbs_file_hash', table_name='knowledge_bases')
    op.create_index(op.f('ix_knowledge_bases_file_hash'), 'knowledge_bases', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_bases_file_hash'), table_name='knowledge_bases')
    op.create_index('ix_kbs_file_hash', 'knowledge_bases', ['file_hash'], unique=False)
    op.drop_column('knowledge_bases', 'noisy_words_generated_at')
    op.drop_column('knowledge_bases', 'noisy_words')
    # ### end Alembic commands ###
